kitchenrun/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('add/', views.add_kitchenrun_property, name='add_kitchenrun_property'),
#    path('add/course/', views.add_kitchenrun_course, name='add_kitchenrun_course'),
    path('<int:event_id>/pair', views.pair_teams, name='kitchenrun_pair_teams'),
    path('<int:event_id>/team', views.kitchenrun_signup, name='kitchenrun_signup'),
    path('<int:event_id>/team-details', views.kitchenrun_team_details, name='kitchenrun_team_details'),
    path('pair/', views.pair_teams, name="pair_teams")
]

main/urls.py
from django.urls import path

from . import views
from .views import add_event
from django.contrib.auth import views as auth_views


urlpatterns = [
    path('', views.index, name='view_index'),
    path('add/', add_event, name='add_event'),
    path('signup/', views.signup, name='signup'),
    path('login/', auth_views.LoginView.as_view(template_name='login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(next_page='login'), name='logout'),
    path('map/', views.map_test, name='map_test'),
    path('event/<int:event_id>/register/', views.register_for_event, name='register_for_event'),
    path('event/<int:event_id>/deregister/', views.deregister_for_event, name='deregister_for_event'),
    path('event/<int:event_id>/', views.event, name='event_detail'),
    path('event/<int:event_id>/edit/', views.add_event, name='event_edit'),
    path('event/<int:event_id>/delete/', views.delete_event, name='event_delete'),
    path('about/', views.about, name='about'),

]

webapp/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.staticfiles.urls import staticfiles_urlpatterns


from webapp import settings

urlpatterns = [
    path('', include('main.urls')),
    path('kitchenrun/', include('kitchenrun.urls')),
    path("admin/", admin.site.urls),

]

if settings.DEBUG:
    urlpatterns += staticfiles_urlpatterns()

kitchenrun/models.py
from django.db import models

import uuid

from main.models import Event,User

import uuid


# Create your models here.

class EventProperty(models.Model):
    # attributes
    event = models.OneToOneField(Event, on_delete=models.CASCADE)
    #applications_start = models.DateTimeField()
    #applications_end = models.DateTimeField()
    #hasAppetizer = models.BooleanField(default=True)
    #hasMainCourse = models.BooleanField(default=True)
    #hasDessert = models.BooleanField(default=True)
    #start_time = models.TimeField()
    length_courses = models.DurationField(default='01:00:00')
    length_breaks = models.DurationField(default='00:30:00')
    #team_size = models.SmallIntegerField(default=3)
    #guests_per_course = models.SmallIntegerField(default=2)
    #course_number = models.SmallIntegerField(default=3)


class Team(models.Model):
    event = models.ForeignKey(Event, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    name = models.CharField(max_length=255)
    street = models.CharField(max_length=255)
    number = models.CharField(max_length=10)
    city = models.CharField(max_length=255)
    address_addition = models.CharField(max_length=255, blank=True)
    lat = models.DecimalField(default=-1, decimal_places=7, max_digits=10)
    lon = models.DecimalField(default=-1, decimal_places=7, max_digits=10)
    is_vegan = models.BooleanField(default=False)
    is_vegetarian = models.BooleanField(default=False)
    is_halal = models.BooleanField(default=False)
    is_kosher = models.BooleanField(default=False)
    allergies = models.TextField(blank=True)
    comments = models.TextField(blank=True)
    team_member_1 = models.CharField(max_length=255)
    team_member_2 = models.CharField(max_length=255)


# class TeamMember(models.Model):
#     team = models.ForeignKey(Team, on_delete=models.CASCADE)
#     name = models.CharField(max_length=255)

# class Course(models.Model):
#     event_property = models.ForeignKey(EventProperty, on_delete=models.CASCADE)
#     name = models.CharField(max_length=255)
#     order = models.SmallIntegerField(default=0)

class Pair(models.Model):
    COURSE_TYPES = [
        (0, 'Appetizer'),
        (1, 'Main Dish'),
        (2, 'Dessert'),
    ]
    event = models.ForeignKey(Event, on_delete=models.CASCADE)
    course = models.SmallIntegerField(
        choices=COURSE_TYPES,
        default=0,
    )
    #course = models.ForeignKey(Course, on_delete=models.CASCADE)
    cook = models.ForeignKey(Team, on_delete=models.CASCADE, related_name="cook_id")
    guest_1 = models.ForeignKey(Team, on_delete=models.CASCADE, related_name="guest_1_id")
    guest_2 = models.ForeignKey(Team, on_delete=models.CASCADE, related_name="guest_2_id")
    #pair_id = models.UUIDField(default=uuid.uuid4)

kitchenrun/forms.py
from django import forms
from .models import EventProperty, Team
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User


class EventPropertyForm(forms.ModelForm):
    class Meta:
        model = EventProperty
        exclude = ['event']  # Excluding owner and participants
        widgets = {
            'length_courses': forms.TextInput(attrs={'placeholder': 'HH:MM:SS'}),
            'length_breaks': forms.TextInput(attrs={'placeholder': 'HH:MM:SS'}),
            'team_size': forms.NumberInput(),
            'guest_per_course': forms.NumberInput(),
            'course_number': forms.NumberInput(),
            # Define other widgets as needed
        }


class TeamForm(forms.ModelForm):
    class Meta:
        model = Team
        exclude = ['event', 'user', 'lat', 'lon']  # Excluding owner and participants
        widgets = {

        }
        labels = {
           'name': "Team Name",
            'street': "Street",
            'number': "Housenumber",
            'team_member_1': "Name of the first team member",
            'team_member_2': "Name of the second team member"

        }
        help_texts = {
            'address_addition': "Address Additions as apartment number or other useful information for finding the address.",
            'is_vegan': "In case one team member is vegetarian activate this checkbox.",
            'is_vegetarian': "In case one team member is vegan activate this checkbox.",
            'is_halal': "In case one team member is halal activate this checkbox.",
            'is_kosher': "In case one team member is kosher activate this checkbox.",
            'comments': "In case you have anything to tell, please provide it here.",


        }

#
# class CourseForm(forms.ModelForm):
#     class Meta:
#         model = Course
#         exclude = ['event_property', 'order']
#         widgets = {
#             'name': forms.TextInput(),
#         }

kitchenrun/views.py
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.db.models import Q
from django.shortcuts import redirect, render, get_object_or_404

from kitchenrun.forms import EventPropertyForm, TeamForm
from kitchenrun.models import EventProperty, Team, Pair
from main.models import Event
from networkx.algorithms import bipartite

import requests
import random
import networkx as nx
from decimal import Decimal

# Create your views here.

def add_kitchenrun_property(request):
    event = Event.objects.get(id = request.session.get('event_id'))
    event_property = EventProperty.objects.filter(event=event).first()
    if request.method == 'POST':
        form = EventPropertyForm(request.POST, instance=event_property)
        if form.is_valid():
            eventProperty = form.save(commit=False)
            eventProperty.event = event
            eventProperty.save()
            messages.success(request, "Event successfully updated.")
            # request.session['number_of_courses'] = eventProperty.course_number
            # request.session['event_property_id'] = eventProperty.id
            return redirect('event_detail', event_id=event.id)  # Redirect to the event dashboard or other page
    else:
        form = EventPropertyForm(instance=event_property)
    return render(request, 'add_kitchenrun_property.html', {'form': form})

def kitchenrun_signup(request, event_id):
    event = get_object_or_404(Event, id=event_id)
    if request.method == 'POST':
        form = TeamForm(request.POST, instance=None)
        if form.is_valid():
            team = form.save(commit=False)
            team.event = event
            team.user = request.user
            event.participants.add(request.user)

            api_url = "https://nominatim.openstreetmap.org/"
            # get lan, lon
            #location = "" + team.street + " " + team.number + ", " + team.city
            api_operator = "search.php"
            api_query = {"street": team.street + " " + team.number, "city": team.city, "format": "jsonv2", "accept-language": "en"}
            api_response = requests.get(api_url + api_operator, params=api_query)
            try:
                team.lat = Decimal(api_response.json()[0]['lat'])
                team.lon = Decimal(api_response.json()[0]['lon'])
            except:
                messages.error(request, "Address was invalid")
                return redirect('kitchenrun_signup', event_id = event.id)

            team.save()
            messages.success(request, "Team successfully created.")
            return redirect('event_detail', event_id=event.id)  # Redirect to the event dashboard or other page
    else:
        form = TeamForm(instance=None)
    return render(request, 'add_team.html', {'form': form})

@login_required
def kitchenrun_team_details(request, event_id):
    event = get_object_or_404(Event, id=event_id)
    event_property = get_object_or_404(EventProperty, event=event)
    team =  get_object_or_404(Team, event=event, user=request.user)
    pairing1 = Pair.objects.all().filter(cook=team)
    pairing2 = Pair.objects.all().filter(guest_1=team)
    pairing3 = Pair.objects.all().filter(guest_2=team)
    pairing = pairing1 | pairing2 | pairing3
    pairing = pairing.order_by('course')

    course_length = event_property.length_courses
    break_length = event_property.length_breaks
    appetizer_time = event.start_time
    main_time = appetizer_time + course_length + break_length
    desert_time = main_time + course_length + break_length

    return render(request, 'team_details.html', {"event": event, "team": team, "pair": pairing, "appetizer_time": appetizer_time, "main_time": main_time, "dessert_time": desert_time, "course_length": course_length})


# def add_kitchenrun_course(request):
#     event_property = EventProperty.objects.get(id=request.session.get('event_property_id'))
#     print(event_property)
#     courses_exist = Course.objects.filter(Q(event_property=event_property)).exists()
#     if courses_exist:
#         # todo make editable courses
#         return redirect('view_index')
#
#     if request.method == 'POST':
#         forms = list()
#         for i in range(request.session.get('number_of_courses')):
#             forms.append(CourseForm(request.POST, prefix=i))
#
#
#         for i in range(len(forms)):
#             if forms[i].is_valid():
#                 course = forms[i].save(commit=False)
#                 course.event_property = event_property
#                 course.order = i
#                 course.save()
#
#         return redirect('view_index')  # Redirect to the event dashboard or other page
#
#
#     else:
#         forms = list()
#         for i in range(request.session.get('number_of_courses')):
#             forms.append(CourseForm(prefix=i))
#         return render(request, 'add_courses.html', {'forms': forms})

def pair_teams(request, event_id):
    event = Event.objects.get(id=event_id)
    event_property = EventProperty.objects.filter(event=event).first()
    courses = ("Starter", "Main", "Desert")
    #courses = Course.objects.filter(event_property=event_property)

    teams = Team.objects.filter(event=event)

    #shuffled_teams = list(teams)


    # number of teams need to be dividable by the number of courses
    assert len(teams) % 3 == 0
    pairs_per_course = (int) (len(teams) / 3)

    # pair teams with courses -> use bipartite matching algorithm (allows to match by course preference later)
    B = nx.Graph()

    # add nodes of type teams
    nodes_teams = [team.id for team in teams]
    random.shuffle(nodes_teams)
    B.add_nodes_from(nodes_teams, bipartite=0)

    # add nodes of type courses
    nodes_courses = list()
    for course in Pair.COURSE_TYPES:
        course_id = course[0]
        for i in range(pairs_per_course):
            nodes_courses.append(str(course_id) + "_" + str(i))
    random.shuffle(nodes_courses)
    B.add_nodes_from(nodes_courses, bipartite=1)

    # add connections between both types
    edges = list()
    for team_id in nodes_teams:
        for course_id_str in nodes_courses:
            parts = course_id_str.split("_")
            if len(parts) == 2 and parts[0].isdigit():
                course_id = int(parts[0])
                if not (team_id == 1 and course_id == 4):
                    edges.append((team_id, course_id_str))
                # add filter here!

    B.add_edges_from(edges)

    results = bipartite.maximum_matching(B)

    # create pair obj out of results
    cooking_teams = (list(), list(), list())
    for team_id, course_id_str in results.items():
        if isinstance(team_id, int) and isinstance(course_id_str, str):
            parts = course_id_str.split("_")
            if len(parts) == 2 and parts[0].isdigit():
                course_id = int(parts[0])
                cooking_teams[course_id].append(Team.objects.get(id=team_id))
                #pair = Pair(
                #    event = event_property,
                #    course = course_id,
                #    team = Team.objects.get(id=team_id),
                #    is_cook = True)
                #pair.save()


    # pair guest teams to cooking teams for each course by rotating the teams of the other courses
    for course in Pair.COURSE_TYPES:
        #cooking_pair = Pair.objects.filter(team=team, is_cook=True).first()
        #course = cooking_pair.course

        course_id = course[0]

        course_appetizer = 0
        course_main = 1
        course_dessert = 2

        if course_id == course_appetizer:
            for i in range(pairs_per_course):
                team = cooking_teams[course_appetizer][i]
                pair = Pair(
                    event = event,
                    course = course_id,
                    cook = team,
                    guest_1 = cooking_teams[course_main][i],
                    guest_2 = cooking_teams[course_dessert][i])
                pair.save()
        
        if course_id == course_main:  
            for i in range(pairs_per_course):
                team = cooking_teams[course_main][i]

                index1 = -1
                if (i+1 < pairs_per_course):
                    index1 = i+1
                else:
                    index1 = i-pairs_per_course+1

                index2 = -1
                if (i+2 < pairs_per_course):
                    index2 = i+2
                else:
                    index2 = i-pairs_per_course+2

                pair = Pair(
                    event = event,
                    course = course_id,
                    cook = team,
                    guest_1 = cooking_teams[course_appetizer][index1],
                    guest_2 = cooking_teams[course_dessert][index2])
                pair.save()

        if course_id == course_dessert:
            for i in range(pairs_per_course):
                team = cooking_teams[course_dessert][i]

                index1 = -1
                if (i+1 < pairs_per_course):
                    index1 = i+1
                else:
                    index1 = i-pairs_per_course+1

                index2 = -1
                if (i+2 < pairs_per_course):
                    index2 = i+2
                else:
                    index2 = i-pairs_per_course+2

                pair = Pair(
                    event = event,
                    course = course_id,
                    cook = team,
                    guest_1 = cooking_teams[course_appetizer][index1],
                    guest_2 = cooking_teams[course_main][index2])
                pair.save()

    #pairs = Pair.objects.filter(event=event_property)

    #w, h = len(teams), len(teams)
    #Matrix = [[0 for x in range(w)] for y in range(h)] 
    #works = True
    #for pair1 in pairs:
    #    for pair2 in pairs:
    #        if  pair1 != pair2 and pair1.pair_id == pair2.pair_id:
    #            Matrix[pair1.team.id-1][pair2.team.id-1] = Matrix[pair1.team.id-1][pair2.team.id-1] + 1

    #print(Matrix)

kitchenrun/templates/add_courses.html
{% extends "base.html" %}
{% block content %}
{% load bootstrap5 %}
<br>
    <h1>Kitchen Run Courses</h1>
<br>
    <form method="post">
        {% csrf_token %}
        {% for form in forms %}
            {% bootstrap_form form %}  <!-- Display the form fields here -->
        {% endfor %}
        <button type="submit" class="btn btn-primary">Add courses</button>
    </form>
{% endblock %}

kitchenrun/templates/add_kitchenrun_property.html
{% extends "base.html" %}
{% block content %}
{% load bootstrap5 %}
<br>
    <h1>Kitchen Run Details</h1>
<br>
    <form method="post">
        {% csrf_token %}
        {% bootstrap_form form %}
        <button type="submit" class="btn btn-primary">Create event</button>
    </form>
{% endblock %}

kitchenrun/templates/add_team.html
{% extends "base.html" %}
{% block content %}
{% load bootstrap5 %}
<br>
    <h1>Kitchen Run Team Signup</h1>
<br>
    <form method="post">
        {% csrf_token %}
        {% bootstrap_form form %}
        <button type="submit" class="btn btn-primary">Register as team</button>
    </form>
{% endblock %}

kitchenrun/templates/pair_teams.html
{% extends "base.html" %}
{% block content %}
{% load bootstrap5 %}
<br>
    <h1>Pair Teams</h1>
<br>
    <p>{{ result }}</p>
    <p>{{ courses }}</p>
    <p>{{ teams }}</p>
{% endblock %}

kitchenrun/templates/team_details.html
{% extends "base.html" %}
{% load bootstrap5 %}
{% load static %}
{% block content %}
<br>
    <div class = ""></div>
    {% if not pair %}
    <div class="alert alert-primary" role="alert">
        Thank you for signing up for the event. The Organizers will start the pairing of the teams soon. Afterwards you will be able to see your personal schedule for the event.
    </div>
    {% endif %}
    <div class = "container card your-team-box mb-3">
        <div class = "card-body">
            <h5>Your Team: {{ team.name }}</h5>
            <p class="card-text">Members: {{ team.team_member_1 }}, {{ team.team_member_2 }}</p>
        </div>
    </div>

  {% if pair %}
    <div class="row g-3"> <!-- Added g-3 class for spacing -->
    {% for p in pair %}
        <div class="col-md-4 d-flex align-items-stretch"> <!-- Added flex utilities -->
            <div class="card course mb-3 w-100"> <!-- Added w-100 for full width -->
                <div class="card-body d-flex flex-column"> <!-- Flex column for internal spacing -->
                    <h5 class="card-title">{{ p.get_course_display }} | 
                        {% if p.course == 0 %} 
                            {{ appetizer_time|date:"TIME_FORMAT" }}
                        {% elif p.course == 1  %}
                            {{ main_time|date:"TIME_FORMAT" }}
                        {% elif p.course == 2  %}
                            {{ dessert_time|date:"TIME_FORMAT" }}
                        {% endif %}</h5>
                    {% if p.cook == team %}
                        <p class="card-text warning small"><i class="bi bi-egg-fried"></i> <strong>You are cooking this course!</strong></p>
                        <p class="card-text alert small">
                            {% if p.cook.is_vegan or p.guest_1.is_vegan or p.guest_2.is_vegan %}<i class="bi "></i> Vegan <br>{% endif %}
                            {% if p.cook.is_vegetarian or p.guest_1.is_vegetarian or p.guest_2.is_vegetarian %}<i class="bi "></i> Vegetarian <br>{% endif %}
                            {% if p.cook.is_halal or p.guest_1.is_halal or p.guest_2.is_halal %}<i class="bi "></i> Halal <br>{% endif %}
                            {% if p.cook.is_kosher or p.guest_1.is_kosher or p.guest_2.is_kosher %}<i class="bi "></i> Kosher <br>{% endif %}
                             Allergies:
                            {% if p.guest_1.allergies != "" and p.guest_2.allergies != "" %}
                                {{ p.guest_1.allergies }} | {{ p.guest_2.allergies }}
                            {% else %}
                                {{ p.guest_1.allergies }}{{ p.guest_2.allergies }}
                            {% endif %}
                            {% if p.guest_1.allergies == "" and p.guest_2.allergies == "" %}
                            No Allergies.
                            {% endif %}
                            <br>
                        </p>
                    {% endif %}
                    <div> <!-- Pushes content to the bottom -->
                        {% if p.cook == team %}
                            <div class="item">
                                <p><i class="bi bi-people"></i> Guests:</p>
                            </div>
                            <div class="item mb-3">
                                <div class="container card1">
                                    <div class="item dark1">
                                        <h5><i class="bi bi-person"></i> Team {{ p.guest_1.name }}</h5>
                                    </div>
                                    <div class="item">
                                        <p>{{ p.guest_1.user.email }}</p>
                                    </div>
                                </div>
                                <div class="container card1">
                                    <div class="item dark1">
                                        <h5><i class="bi bi-person"></i> Team {{ p.guest_2.name }}</h5>
                                    </div>
                                    <div class="item">
                                        <p>{{ p.guest_2.user.email }}</p>
                                    </div>
                                </div>
                            </div>
                        {% else %}
                            <div class="item">
                                <p><i class="bi bi-house"></i> Host: Team {{ p.cook.name }}</p>
                            </div>
                            <div class="item">
                                <p><i class="bi bi-envelope"></i> {{ p.cook.user.email }}</p>
                            </div>
                            <div class="item">
                                <p><i class="bi bi-geo-alt"></i> Location: {{ p.cook.street }} {{ p.cook.number }}, {{ p.cook.city }}<br>{{ p.cook.address_addition }}</p>
                            </div>
                        {% endif %}
                    </div>
                    <div class="mt-auto"></div>
                </div>
            </div>
        </div>
    {% endfor %}
    </div>
{% endif %}




    <script src="{% static 'map/apikey.js' %}"></script>
    <!-- Leaflet -->
    <link rel="stylesheet" href="{% static 'map/leaflet/leaflet.css' %}"/>
    <script src="{% static 'map/leaflet/leaflet.js' %}"></script>
    <link rel="stylesheet" href="{% static 'map/map.css' %}"/>
    <link rel="stylesheet" href="{% static 'style.css' %}"/>
    <!-- Leaflet Routing Machine -->
    <link rel="stylesheet" href="{% static 'map/leaflet-routing/dist/leaflet-routing-machine.css' %}"/>
    <script src="{% static 'map/leaflet-routing/dist/leaflet-routing-machine.js' %}"></script>
    <script src="{% static 'map/lrm-graphhopper.js' %}"></script>

    <!-- Map -->
    <div id="map{{p.course}}"></div>
    <script> var disable_routing = true; var destination = [{{ event.lat }}, {{ event.lon }}] ;</script>
    <script>
        var markers = [[{{ team.lat }}, {{ team.lon }}], [{{ pair.first.guest_1.lat }}, {{ pair.first.guest_1.lon }}], [{{ pair.first.guest_2.lat }}, {{ pair.first.guest_2.lon }}]];
        console.log(markers);
    </script>
    <script src="{% static 'map/map.js' %}"></script>
    <br>
    <br>
<br>
{% endblock %}